services:
  - type: web
    name: minecraft-server
    env: node
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /
